Create U-22反省.md
kbc-itw/journal pull request #22
Opened 2017-08-29 08:53 UTC by nakamuratomohiko

反省点を書いたページ

2017-08-29 08:53 UTC, nakamuratomohiko commented
日本語のおかしいところがないかをチェックして取り込んでくれ

2017-09-05 06:56 UTC, wamekukyouzin requested changes
+ 箇条書きにおいて末尾に句点は必要ない。また、直後に丸カッコが来る場合、丸カッコの後に配置する
+ 「考慮していないことで」は、より因果関係のわかりやすい「考慮していなかったため」の方がよい
+ 「進まない状態が生じた」より「進まなかった」のほうがよい
+ 「頼れなかった」は口語的なので、「人に頼ることができなかった」等に書き換える

2017-09-05 13:49 UTC, nakamuratomohiko commented
指摘された箇所を変更した

2017-09-06 06:03 UTC, wamekukyouzin approved these changes

2017-09-07 07:03 UTC, merged